language: ruby
bundler_args: --without development
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - jruby-9.0.5.0
  - rbx-3.107