language: ruby
bundler_args: --without development
before_install:
  - gem install bundler -v '< 2'
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - jruby-9.0.5.0
  - rbx-3.107
matrix:
  include:
    - rvm: 2.3.0
      env: RUBY_VERS = 2.3.0
    - rvm: 2.2.4
      env: RUBY_VERS = 2.2.4
    - rvm: 2.1.8
      env: RUBY_VERS = 2.1.8
    - rvm: jruby-9.0.5.0
      env: RUBY_VERS = 2.2
    - rvm: rbx-3.107
      env: RUBY_VERS = 3
before_script:
  - if env(RUBY_VERS) = true; bundle update --bundler; fi
  