language: ruby
bundler_args: --without development
before_install:
  - gem install bundler -v '< 2'
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - jruby-9.0.5.0
  - rbx-3.107
matrix:
  include:
    - 2.3.0
    env: RUBY_VERS = 2.3.0
  include:
    - 2.2.4
    env: RUBY_VERS = 2.2.4
  include:
    - 2.1.8
    env: RUBY_VERS = 2.1.8
  include:
    - jruby-9.0.5.0
    env: RUBY_VERS = 2.2
  include:
    - rbx-3.107
    env: RUBY_VERS = 3
script:
  if: RUBY_VERS >= 2.3
  - bundle update --bundler