dist: trusty
language: ruby
bundler_args: --without development
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - jruby-9.2.11.0

jobs:
  # Use `fast_finish`, don't wait for any allowed failures.
  fast_finish: true

  include:
    - name: Rubinius
      rvm: rbx-3.107
      dist: trusty
  
  allow_failures:
    - name: Rubinius
 
