dist: xenial
language: ruby
bundler_args: --without development
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - jruby-9.0.5.0

matrix:
  fast_finish: true

  include:
    - name: Rubinius
      rvm: rbx-2.2.7
      dist: trusty

  allow_failures:
    - name: Rubinius
